version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <Task-Definition-ARN>
        LoadBalancerInfo:
          ContainerName: "web-app-container"
          ContainerPort: 80