version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:eu-west-1:631204218401:task-definition/WebAppTaskDefinition:3"
        LoadBalancerInfo:
          ContainerName: "web-app-container"
          ContainerPort: 80