version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 631204218401.dkr.ecr.eu-west-1.amazonaws.com
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - REPOSITORY_URI=631204218401.dkr.ecr.eu-west-1.amazonaws.com/web-app-repo
      - export IMAGE_URI=$REPOSITORY_URI:$IMAGE_TAG
      - echo "Built image URI: $IMAGE_URI"

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE_URI .
      - docker push $IMAGE_URI

  post_build:
    commands:
      - echo "[{\"name\":\"web-app-container1\",\"imageUri\":\"$IMAGE_URI\"}]" > imagedefinitions.json
      - echo Rendering taskdef_final.json...
      - envsubst < taskdef.json > taskdef_final.json

artifacts:
  files:
    - appspec.yaml
    - taskdef_final.json
  name: BuildArtifact
  discard-paths: yes
