version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - REPOSITORY_URI=631204218401.dkr.ecr.eu-west-1.amazonaws.com/web-app-repo
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - IMAGE_URI=$REPOSITORY_URI:$IMAGE_TAG

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
      - echo "IMAGE_URI=$REPOSITORY_URI:$IMAGE_TAG"
      - echo "IMAGE_URI=$REPOSITORY_URI:$IMAGE_TAG" >> $CODEBUILD_SRC_DIR/image_uri.env
      - export IMAGE_URI

  post_build:
    commands:
      - IMAGE1_NAME=$REPOSITORY_URI:$IMAGE_TAG
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"web-app-container1","imageUri":"%s"}]' $IMAGE_URI > imageDefinitions.json
      - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
      - cat imageDetail.json
      - . $CODEBUILD_SRC_DIR/image_uri.env
      - envsubst < taskdef.json > taskdef_final.json
      - cat taskdef_final.json
      - echo $IMAGE_URI >> imagename.json
      - cat imagename.json


artifacts:
  files:
    - appspec.yaml
    - taskdef_final.json
    - imageDefinitions.json
  name: BuildArtifact
  discard-paths: yes



